# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Seasoned Code
tagline:          'Software with a little spice'
description:      'Software development, some home cooking and everything in between'
url:              https://seasoned-code.com
baseurl:          # the optional subpath of your site, e.g. "/blog"
google_analytics: 'UA-110802329-1'

author:
  name:           'Gregory A. Owen'
  url:            https://twitter.com/seasoned_code

gitgraph:
  src: '/assets/script/gitgraph.js'

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Sidebar link settings
sidebar_home_link:  true
github:
  repo:             https://github.com/seasoned-code

# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
