# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Seasoned Code
tagline:          'Software with a little spice'
description:      'Software development, some home cooking and everything in between'
url:              https://seasoned-code.com
baseurl:          # the optional subpath of your site, e.g. "/blog"
google_analytics: 'UA-110802329-1'

author:
  name:           'Gregory A. Owen'
  url:            https://twitter.com/seasoned_code

paginate:         5

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Custom vars
version:            3.4.1
sidebar_home_link:  true
github:
  repo:             https://github.com/seasoned-code